services:
  mulherplena:
    image: mulherplena:latest
    build: .
    restart: unless-stopped
    ports:
      - "127.0.0.1:8081:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mulherplena.rule=Host(`mulherplena.sni.org.br`)"
      - "traefik.http.routers.mulherplena.entrypoints=websecure"
      - "traefik.http.routers.mulherplena.tls.certresolver=letsencrypt"
      - "traefik.http.services.mulherplena.loadbalancer.server.url=http://127.0.0.1:8081"
