// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://byslxrvqzcrjgpoatyxt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5c2x4cnZxemNyamdwb2F0eXh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU5ODExOTEsImV4cCI6MjA4MTU1NzE5MX0.LwgHCSML5e6lRqGpLcWWcLrKTUapdqlrJbaNUGOIips";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});